### ISSUE TITLE
patch multiple-empty-lines to error and disallow more than one

### ISSUE THREAD

**Issue by generalandrew** [RevoltTV/eslint-config-revolt#1]
This will eliminate duplicate lines in our services. 

I could see how this would be breaking for older services, should it be a version number change instead of a patch?

**Comment by andrewburgess** [comment]
How is it breaking?

**Comment by andrewburgess** [comment]
Make it a minor version change

**Comment by generalandrew** [comment]
My concern on breaking is if we were to update this file in the older code base and if we missed any newlines then this would prevent the production code from starting up.

**Comment by andrewburgess** [comment]
It should be something caught on the build server, and lint errors need to be fixed before going to production anyways
